version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean package  > /dev/null
      - pwd
      - ls -lrta
      - pwd
      - whoami
      - date +"%d-%m-%y" && date "+%T"
  post_build:
    commands:
      ## aws s3 cp target/*.war s3://xxxxxxxxxxxx . We don't need this step.
      - ls -lrta target/
      - pwd
      - whoami
      - date +"%d-%m-%y" && date "+%T"
      - echo Build completed
artifacts:
  files:
    - target/*.jar
    - scripts/server_start.sh
    - scripts/server_stop.sh
    - scripts/server_validate.sh
    - appspec.yml

  discard-paths: yes
