version: 0.2

phases:
  pre_build:
    commands:
      - ls -lrta
      - chmod 777 -R *
      - pwd
      - whoami
      - date +"%d-%m-%y" && date "+%T"
      - myPath=$(pwd)
      - echo ${myPath}
      # ############################################# ##
      # #env variables(Need change for different env) ##
      - jarFileName="pac-batch-ec2-0.1.jar"
      # #env variables(Need change for different env) ##
      # ############################################# ##
  build:
    commands:
      - yum remove java-* -y -q
      - yum update -y -q && yum install -y -q java-11-amazon-corretto && yum clean all
      - wget -O /tmp/apache-maven-3.8.6-bin.zip https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip
      - unzip -d /tmp/ /tmp/apache-maven-3.8.6-bin.zip
      - mkdir -p /usr/bin/maven
      - mv /tmp/apache-maven-3.8.6/* /usr/bin/maven/
      - export PATH=/usr/bin/maven/bin:${PATH}
      - mvn -v  
      - mvn clean package  > /dev/null
      - pwd
      - ls -lrta
      - pwd
      - whoami
      - date +"%d-%m-%y" && date "+%T"
  post_build:
    commands:
      ## aws s3 cp target/*.war s3://xxxxxxxxxxxx . We don't need this step.
      - ls -lrta target/
      - pwd
      - whoami
      - date +"%d-%m-%y" && date "+%T"
      - echo Build completed
artifacts:
  files:
    - target/${jarFileName}
    - scripts/server_start.sh
    - scripts/server_stop.sh
    - scripts/server_validate.sh
    - appspec.yml

  discard-paths: yes
